# Generated by Django 4.2 on 2026-09-23 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_contactlead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactlead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Richiesta di contatto', 'verbose_name_plural': 'Richieste di contatto'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Socio', 'verbose_name_plural': 'Soci'},
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ricevuta il'),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Città'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Numero civico'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_province',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Via'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Iscritto il'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modifica'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='member',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.region', verbose_name='Regione'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('attivo', 'Attivo'), ('inattivo', 'Inattivo'), ('sospeso', 'Sospeso')], default='attivo', max_length=20, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tessera_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero tessera'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
    ]
