# Generated by Django 4.2 on 2026-03-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_text',
            field=models.TextField(blank=True, default='Con il tuo contributo possiamo ampliare i servizi e raggiungere più famiglie. Ogni donazione conta.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(blank=True, default='Sostieni il nostro lavoro', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_text',
            field=models.TextField(blank=True, default='Iniziative locali e nazionali pensate per migliorare la vita quotidiana delle famiglie.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_title',
            field=models.CharField(blank=True, default='Progetti in evidenza', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta_link',
            field=models.CharField(blank=True, default='join.html', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_cta_text',
            field=models.CharField(blank=True, default='Iscriviti', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_link',
            field=models.CharField(blank=True, default='support.html', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_cta_text',
            field=models.CharField(blank=True, default='Sostienici', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_text',
            field=models.TextField(blank=True, default='Promuovere politiche che mettano al centro la famiglia, il lavoro dignitoso e la coesione sociale. Trasparenza, responsabilità e partecipazione civica guidano ogni nostra iniziativa.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_title',
            field=models.CharField(blank=True, default='La nostra missione', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Sosteniamo politiche concrete per la famiglia, il lavoro e la solidarietà. Partecipa, iscriviti, dona: costruisci con noi un futuro più sicuro per i tuoi cari.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Per le famiglie, per il futuro — Un paese più forte insieme', max_length=255),
        ),
    ]
