# Generated by Django 4.2 on 2026-03-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('website', '0002_homepage_cta_text_homepage_cta_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedSitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('target_slug', models.SlugField(help_text='Slug-ul rutei existente, ex: index, about, projects', max_length=100, unique=True)),
                ('html_content', models.TextField(blank=True, help_text='Conținut HTML complet pentru pagina target. Dacă este gol, se folosește fallback-ul static.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
