# Generated by Django 4.2 on 2026-03-01 20:24

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_homevaluecard_homefeaturedcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('cta', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'doc-full'}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('white', 'White')], 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('button_text', 4), ('button_url', 4), ('button_style', 5)]], {'icon': 'placeholder'})}),
        ),
    ]
