# Generated by Django 4.2 on 2026-03-01 20:28

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_standardpage_content_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='layout_preset',
            field=models.CharField(choices=[('custom', 'Custom (empty)'), ('about', 'About preset'), ('projects', 'Projects preset'), ('support', 'Support preset'), ('join', 'Join preset'), ('contact', 'Contact preset')], default='custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('cta', 6), ('cards_grid', 10), ('faq', 15), ('image_text_split', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'doc-full'}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('white', 'White')], 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('button_text', 4), ('button_url', 4), ('button_style', 5)]], {'icon': 'placeholder'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Columns'), ('3', '3 Columns')], 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('cta_text', 4), ('cta_url', 4)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 4), ('columns', 7), ('items', 9)]], {'icon': 'list-ul'}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Domande frequenti', 'required': False}), 12: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 13: ('wagtail.blocks.StructBlock', [[('question', 2), ('answer', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 11), ('items', 14)]], {'icon': 'help'}), 16: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image Left'), ('right', 'Image Right')], 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 16), ('image', 17), ('image_position', 18), ('cta_text', 4), ('cta_url', 4)]], {'icon': 'image'})}),
        ),
    ]
