# Generated by Django 4.2 on 2026-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_standardpage_layout_preset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='layout_preset',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_primary_cta_link',
            field=models.CharField(blank=True, default='/join/', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_secondary_cta_link',
            field=models.CharField(blank=True, default='/support/', max_length=255),
        ),
    ]
