# Generated by Django 4.2 on 2026-09-23 05:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_backfill_wagtail_localize_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('cta', 7), ('cards_grid', 14), ('faq', 20), ('image_text_split', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Titolo'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'doc-full', 'label': 'Paragrafo'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo', 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Testo', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Testo del pulsante', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es. /join/ (iscrizione), /sciarrone/contact/ (contatti) o un indirizzo completo https://… Sulle pagine in inglese aggiungi /en davanti: /en/join/, /en/sciarrone/contact/.', 'label': 'Link del pulsante', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Arancione'), ('secondary', 'Solo contorno'), ('white', 'Solo contorno (chiaro)')], 'label': 'Stile del pulsante', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('button_text', 4), ('button_url', 5), ('button_style', 6)]], {'icon': 'placeholder', 'label': 'Riquadro con pulsante'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo della sezione', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 colonne'), ('3', '3 colonne')], 'label': 'Colonne', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Testo del link', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es. /join/ (iscrizione), /sciarrone/contact/ (contatti) o un indirizzo completo https://… Sulle pagine in inglese aggiungi /en davanti: /en/join/, /en/sciarrone/contact/.', 'label': 'Link', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('cta_text', 10), ('cta_url', 11)]], {'label': 'Scheda'}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Schede', 'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('title', 8), ('columns', 9), ('items', 13)]], {'icon': 'list-ul', 'label': 'Griglia di schede'}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Domande frequenti', 'label': 'Titolo della sezione', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Domanda', 'required': True}), 17: ('wagtail.blocks.RichTextBlock', (), {'label': 'Risposta', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('question', 16), ('answer', 17)]], {'label': 'Domanda'}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Domande', 'min_num': 1}), 20: ('wagtail.blocks.StructBlock', [[('title', 15), ('items', 19)]], {'icon': 'help', 'label': 'Domande frequenti'}), 21: ('wagtail.blocks.RichTextBlock', (), {'label': 'Testo', 'required': False}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Immagine', 'required': True}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Immagine a sinistra'), ('right', 'Immagine a destra')], 'label': "Posizione dell'immagine", 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 21), ('image', 22), ('image_position', 23), ('cta_text', 4), ('cta_url', 5)]], {'icon': 'image', 'label': 'Immagine e testo'})}),
        ),
    ]
