# Generated by Django 4.2 on 2026-09-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_standardpage_content_blocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepage'},
        ),
        migrations.AlterModelOptions(
            name='standardpage',
            options={'verbose_name': 'Pagina', 'verbose_name_plural': 'Pagine'},
        ),
    ]
