# Generated by Django 4.2 on 2026-09-23 06:27

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_homepage_options_alter_standardpage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefeaturedcard',
            name='text',
            field=models.TextField(verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='homefeaturedcard',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titolo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_text',
            field=models.TextField(blank=True, default='Con il tuo contributo possiamo ampliare i servizi e raggiungere più famiglie. Ogni donazione conta.', verbose_name='Testo del riquadro finale'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(blank=True, default='Sostieni il nostro lavoro', max_length=255, verbose_name='Titolo del riquadro finale'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_text',
            field=models.TextField(blank=True, default='Iniziative locali e nazionali pensate per migliorare la vita quotidiana delle famiglie.', verbose_name='Testo dei progetti in evidenza'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_title',
            field=models.CharField(blank=True, default='Progetti in evidenza', max_length=255, verbose_name='Titolo dei progetti in evidenza'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_primary_cta_text',
            field=models.CharField(blank=True, default='Iscriviti', max_length=100, verbose_name='Testo del pulsante arancione'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_secondary_cta_text',
            field=models.CharField(blank=True, default='Sostienici', max_length=100, verbose_name='Testo del pulsante bianco'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Sosteniamo politiche concrete per la famiglia, il lavoro e la solidarietà. Partecipa, iscriviti, dona: costruisci con noi un futuro più sicuro per i tuoi cari.', verbose_name='Sottotitolo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Per le famiglie, per il futuro — Un paese più forte insieme', max_length=255, verbose_name='Titolo principale'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_text',
            field=models.TextField(blank=True, default='Promuovere politiche che mettano al centro la famiglia, il lavoro dignitoso e la coesione sociale. Trasparenza, responsabilità e partecipazione civica guidano ogni nostra iniziativa.', verbose_name='Testo della missione'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission_title',
            field=models.CharField(blank=True, default='La nostra missione', max_length=255, verbose_name='Titolo della missione'),
        ),
        migrations.AlterField(
            model_name='homevaluecard',
            name='text',
            field=models.TextField(verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='homevaluecard',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titolo'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('cta', 7), ('cards_grid', 14), ('faq', 20), ('image_text_split', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Titolo'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'doc-full', 'label': 'Paragrafo'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo', 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Testo', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Testo del pulsante', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es. /join/ (iscrizione), /sciarrone/contact/ (contatti) o un indirizzo completo https://… Sulle pagine in inglese aggiungi /en davanti: /en/join/, /en/sciarrone/contact/.', 'label': 'Link del pulsante', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Arancione'), ('secondary', 'Solo contorno'), ('white', 'Solo contorno (chiaro)')], 'label': 'Stile del pulsante', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('button_text', 4), ('button_url', 5), ('button_style', 6)]], {'icon': 'placeholder', 'label': 'Riquadro con pulsante'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Titolo della sezione', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 colonne'), ('3', '3 colonne')], 'label': 'Colonne', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Testo del link', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Es. /join/ (iscrizione), /sciarrone/contact/ (contatti) o un indirizzo completo https://… Sulle pagine in inglese aggiungi /en davanti: /en/join/, /en/sciarrone/contact/.', 'label': 'Link', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('cta_text', 10), ('cta_url', 11)]], {'label': 'Scheda'}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Schede', 'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('title', 8), ('columns', 9), ('items', 13)]], {'icon': 'list-ul', 'label': 'Griglia di schede'}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Domande frequenti', 'label': 'Titolo della sezione', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Domanda', 'required': True}), 17: ('wagtail.blocks.RichTextBlock', (), {'label': 'Risposta', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('question', 16), ('answer', 17)]], {'label': 'Domanda'}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Domande', 'min_num': 1}), 20: ('wagtail.blocks.StructBlock', [[('title', 15), ('items', 19)]], {'icon': 'help', 'label': 'Domande frequenti'}), 21: ('wagtail.blocks.RichTextBlock', (), {'label': 'Testo', 'required': False}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Immagine', 'required': True}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Immagine a sinistra'), ('right', 'Immagine a destra')], 'label': "Posizione dell'immagine", 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 21), ('image', 22), ('image_position', 23), ('cta_text', 4), ('cta_url', 5)]], {'icon': 'image', 'label': 'Immagine e testo'})}, verbose_name='Blocchi di contenuto'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Introduzione'),
        ),
    ]
